# windows mingw makefile

CC = g++
CFLAGS = -std=c++11

BIN	 = main
OBJS = Bios.o Cpu.o Interconnect.o main.o

INCDIRS = 

LIBDIRS =

LIBS = 

all: $(OBJS)
	$(CC) $(CFLAGS) -o $(BIN) $(OBJS) $(INCDIRS) $(LIBDIRS) $(LIBS)

%.o: %.cpp
	$(CC) $(CFLAGS) -c -o $@ $< $(INCDIRS)
	
clean:
	rm -r $(OBJS) $(BIN)
